services:
  backend:
    build: ./backend
    ports:
      - "1234:1234"
    env_file: ./backend/.env
    environment:
      - PORT=1234

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    env_file: ./frontend/.env
    depends_on:
      - backend
